set -e

SELF_FOLDER=$(dirname "$0")
ROOT_PATH="$SELF_FOLDER/.."
SRC_PATH="$ROOT_PATH/protocol"
DST_PATH="$ROOT_PATH/origin_platform/models/autogenerated"

echo $DST_PATH

protoc -I="$SRC_PATH" --proto_path="$ROOT_PATH" --python_betterproto_out="$DST_PATH" "$SRC_PATH/measurements/messages.proto"
#protoc -I="$SRC_PATH" --python_betterproto_out="$DST_PATH" "$SRC_PATH/meteringpoints.proto"
#protoc -I="$SRC_PATH" --python_betterproto_out="$DST_PATH" "$SRC_PATH/users.proto"
