"""
Global topics on the message bus.
"""

AUTH = 'PO-AUTH'
CERTS = 'PO-CERTS'
DELEGATES = 'PO-DELEGATES'
KEYS = 'PO-KEYS'
MEASUREMENTS = 'PO-MEASUREMENTS'
MEASUREMENTS_COMMANDS = 'PO-MEASUREMENTS-COMMANDS'
METERINGPOINTS = 'PO-METERINGPOINTS'
METERINGPOINTS_COMMANDS = 'PO-METERINGPOINTS_COMMANDS'
TECHNOLOGIES = 'PO-TECHNOLOGIES'
USERS = 'PO-USERS'
