# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: measurements.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime

import betterproto


@dataclass
class Measurement(betterproto.Message):
    gsrn: str = betterproto.string_field(1)
    amount: int = betterproto.int32_field(2)
    begin: datetime = betterproto.message_field(3)
    end: datetime = betterproto.message_field(4)


@dataclass
class NewMeasurement(betterproto.Message):
    measurement: "Measurement" = betterproto.message_field(1)
